### PR TITLE
Not necessary to pin the dependencies, and likely..

### PR DESCRIPTION
**Pull request by bram2000**
to cause more annoying problems

### CODE REVIEW

**Comment by bram2000** [comment]
Ironically the recent breakage was actually caused by having (incomplete) pinned dependencies. Also the iw-data-test-pandas repo does not pin things. Alternatively I could pin everything, but things like e.g new python versions could break things, while if unpinned you might get occasional breakages but they should be very short lived.

**Comment by JamesFoxJS** [comment]
For this repo, my gut feel is to err on the side of stability, the reason being that, as interviewers, we might go several weeks without looking at it and then an interview comes along and we're in a time-pressured environment. Can you invite another review as a casting vote? Josh?

**Comment by bram2000** [comment]
No problem, I will pin them all!

**Comment by bram2000** [comment]
Closed in favour of https://github.com/infinityworks/iw-data-test-python/pull/6

**Pull request closed without merging**
